apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
  labels:
    application: data-service
spec:
  template:
    spec:
      containers:
        - env:
            - name: "AB_OFF"
              value: "true"
            - name: "AB_JOLOKIA_OFF"
              value: "true"
            - name: ACCOUNTS_DB_USERNAME
              value: test_user
            - name: ACCOUNTS_DB_PASSWORD
              value: test_pass
            - name: ACCOUNTS_DATABASE_NAME
              value: ACCOUNTS
            - name: ACCOUNTS_DATABASE_HOST
              value: mysql-accounts
            - name: ACCOUNTS_DATABASE_PORT
              value: 3306
            - name: JAVA_OPTIONS
              value: "-Dswarm.datasources.data-sources.ACCOUNTS_DS.connection-url=jdbc:mysql://$(ACCOUNTS_DATABASE_HOST):$(ACCOUNTS_DATABASE_PORT)/$(ACCOUNTS_DATABASE_NAME) 
                      -Dswarm.datasources.data-sources.ACCOUNTS_DS.user-name=$(ACCOUNTS_DB_USERNAME) 
                      -Dswarm.datasources.data-sources.ACCOUNTS_DS.password=$(ACCOUNTS_DB_PASSWORD) 
                      -Dswarm.datasources.data-sources.ACCOUNTS_DS.driver-name=mysql
                      -DAB_JOLOKIA_OFF=true"
                                         
